### ISSUE TITLE
win10 运行出错后 图片所在文件夹 所有文件丢失！！！！！！

### ISSUE THREAD

**Issue by xujunhe** [jiazheng/BaiduMapTileCutter#5]
win10 运行出错后 图片所在文件夹 所有文件丢失！！！！！！ 所有文件丢失！！！所有文件丢失    我辛辛苦苦写了一个礼拜的文档啊

**Comment by jiazheng** [comment]
实在抱歉啊。不过不建议把重要文档放在生成图片所在的目录。后续我会完善这里的逻辑。

**Comment by jiazheng** [comment]
已经完善这里的逻辑，不再删除输出目录下已有的文件。
